---
title: "Global Health Research"
resource_files:
- 702.Rmd
- css/custom-learnr.css
- images/logo_dark.png
- images/logo.png
- favicon.ico
runtime: shiny_prerendered
output:
  learnr::tutorial:
    css: css/custom-learnr.css
subtitle: GLHLTH 702, Duke University
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## Syllabus

### Fall 2019

### Instructional Team

**Instructor**: [Eric Green, Ph.D.](https://globalhealth.duke.edu/people/faculty/green-eric){target="_blank"}, Duke University

**Teaching Assistant**: TBA

### Overview

This course will introduce you to research designs and methods in global health. Global health is a multi-disciplinary field, so we will consider approaches common to the behavioral and social sciences, public health, and medicine.

Our primary interest will be the study of causal inference. In global health, we are often interested in knowing what treatments, programs, interventions, and policies "work" and why. To answer questions of impact, we often turn to randomized controlled trials, a mainstay of medical research. As such, we will spend time exploring the rationale, process, and limitations of field experiments.

Randomization is not always possible or advisable, however, and researchers must build a causal argument using non-experimental methods. We will review several approaches, consider relevant threats to causal inference, and discuss how to improve non-experimental research designs.

Along the way, we will cover research basics, such as asking evidence-based research questions, searching the literature, developing a theory of change, identifying indicators and collecting data, selecting research participants, and testing hypotheses. In the latter part of the course, we will turn to more specialized topics in global health research, such as writing research proposals and manuscripts, economic analyses, and making an impact.

### Course Goals and Learning Objectives

We have two broad goals this semester:

1. to make you a better consumer of research; and
2. to help you design your first study.

<br>

The course is divided into six modules:

1. Getting started with global health research
2. Define your study aims
3. Select a research design
4. Specify your methods
5. Practice good science
6. Make an impact with your work

<br>

By the end of the semester, you should be able to:

* Describe the landscape of global health research
* Begin developing research ideas
* Effectively search the literature and make use of systematic reviews and meta-analyses
* Critically appraise scientific work 
* Ask a good research question and develop study aims and hypotheses 
* Develop a theory of change and logic model
* Identify indicators to measure throughout the causal chain
* Understand the fundamental challenge of causal inference and strategies for building a causal argument
* Articulate the benefits and limitations of random assignment
* Explain the logic and limitations of different quasi-experimental and observational designs that can be used when randomization is not possible or ethical
* Select the best method of data collection given study objectives and resources
* Devise a sampling strategy to meet study objectives and resources
* Design a high-powered study
* Describe common challenges when building research collaborations and articulate strategies for being a good collaborator
* Understand the process of ethical review
* Explain the benefits of open science practices to colleagues
* Understand how scientists share their work by publishing and giving talks at conferences
* Make a plan to promote the use of research in policymaking

### Class Format

Each class session has a dedicated tutorial page that introduces the session and explains how to prepare for class. Class sessions will typically begin with a brief lecture designed to reinforce or extend pre-class learning, but the aim is to spend most of the in-class time on application activities. Activities will be based on assigned readings and will incorporate the use of tools like R/RStudio. Please review the activity before class, just as you might prepare for a lab in biology or chemistry.

You: Hey, your in-class mini-lectures are the same as the videos you posted. That's lame. 

Me: You don't have to watch the videos before class. We post them to help students who like repetition and to allow those who miss class to catch up.

You: Can I skip class?

Me: Sure, but you have to make up the in-class activity if you want the credit.

You: I don't like your jokes in person or on video.

Me: 

<iframe src="https://giphy.com/embed/pPhyAv5t9V8djyRFJH" width="480" height="350" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/wtf-obama-wth-pPhyAv5t9V8djyRFJH">via GIPHY</a></p>

### Resources

The main course text is [*Global Health Research: Designs and Methods*](https://themethodsection.com/){target="_blank"}. You can read it online for free, download a PDF, or get a version for iBooks. I do not recommend reading on a mobile device unless you use the iBooks version.

I encourage you to watch or listen to all of the embedded media throughout the book, but only media embedded in the main text is required. Media embedded in the margin notes is optional.

### Workload

A reasonable rule of thumb is somewhere between 2:1 and 3:1 out-of-class to in-class hours. At the upper end, this is about 100 hours of outside class time this semester.

### Evaluation

Your final grade will be a weighted average of several components: application activities, homework, a midterm exam, and a study proposal.

**In-class application activities**: Short activities designed to be completed in class in groups of 2-3. Pass/fail.

**Homework**: Assignments generally due one week after the end of the module.

**Midterm**: There will be an in-class midterm exam. Multiple-choice, fill-in-the-blank, and short answer questions.

**Study proposal**: Your study proposal will take the place of the final exam. Details on format and process will be provided.

| Component                             | Weight |
|:----                                  |:--:    |
| In-class application activities       | 20%    |
| Homework                              | 20%    |
| Midterm                               | 25%    |
| Study proposal                        | 35%    |

Ranges for letter grades will be set at the end of the semester, and grades may be curved. Cumulative scores of at least 90, 80, and 70 will be guaranteed at least an A-, B-, and C-, respectively. 

### Policies

Please note the following:

* If you miss an in-class **application activity**, you will have until the start of the next class to contact the TA and submit your completed work. After this time, you will receive a score of 0 unless you have permission to follow a different schedule. [See here](https://trinity.duke.edu/undergraduate/academic-policies/class-attendance-and-missed-work){target="_blank"} for more details about Duke's policies regarding class attendance and missed work.
* **Homework** will be due at the start of class on the date indicated on the schedule. Late submissions will penalized 5 percentage points. For every 24 hours late after the missed deadline, an additional 5 percentage points will be deducted from the score.
* Students should abide by the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard){target="_blank"} at all times. If a questionable circumstance arises, do not hesitate to seek my guidance (before is always better than after).
* Any student with a documented disability needing academic adjustments or accommodations should speak with me during the first two weeks of class. All discussions will remain confidential. Students with disabilities will also need to contact the [Student Disability Access Office](http://www.access.duke.edu/students/requesting/index.php){target="_blank"}.


## M1: Getting Started

By the end of this module, you should be able to:

* Describe the landscape of global health research
* Begin developing research ideas
* Effectively search the literature and make use of systematic reviews and meta-analyses
* Critically appraise scientific work 

<br>

#### Class Sessions

| Date    | Session             | 
|:---------|:--------------------|
| Aug 27  | [1.1 Welcome](https://try.themethodsection.com/s01-1){target="_blank"} |
| Aug 29  | [1.2 Global health research](https://try.themethodsection.com/duke/s01-2){target="_blank"} |
| Sept 3  | [1.3 Developing research ideas](){target="_blank"} |
| Sept 5  | [1.4 Systematic reviews and meta-analyses](){target="_blank"} |
| Sept 10 | [1.5 Critical appraisal]() |

<br>

#### Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| TBA                           | TBA      |

## M2: Define Your Study Aims

By the end of this module, you should be able to:

* Ask a good research question and develop study aims and hypotheses 
* Develop a theory of change and logic model
* Identify indicators to measure throughout the causal chain

<br>

#### Class Sessions

| Date    | Session             | 
|:---------|:--------------------|
| Sept 12  | [2.1 Research questions and aims](){target="_blank"} |
| Sept 17  | [2.2 The role of theory](){target="_blank"} |
| Sept 19  | [2.3 Outcomes and indicators](){target="_blank"} |


#### Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| TBA                           | TBA      |

## M3: Select a Research Design

By the end of this module, you should be able to:

* Understand the fundamental challenge of causal inference and strategies for building a causal argument
* Articulate the benefits and limitations of random assignment
* Explain the logic and limitations of different quasi-experimental and observational designs that can be used when randomization is not possible or ethical

#### Class Sessions

| Date    | Session             | 
|:---------|:--------------------|
| Sept 24  | 3.1 Research designs and causal inference |
| Sept 26  | 3.2 Experimental designs |
| Oct 1  | 3.3 Quasi-experimental designs |
| Oct 3  | 3.4 Observational designs |
<!--
| Sept 24  | [3.1 Research designs and causal inference](){target="_blank"} |
| Sept 26  | [3.2 Experimental designs](){target="_blank"} |
| Oct 1  | [3.3 Quasi-experimental designs](){target="_blank"} |
| Oct 3  | [3.4 Observational designs](){target="_blank"} |
-->


<br>

#### Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| TBA                           | TBA      |

## Midterm

| Date    | Session             | 
|:---------|:--------------------|
| Oct 10  | Selecting a research design |
| Oct 15  | Review |
| Oct 17  | Midterm |
| Oct 22  | Midterm results, introduction of final project |
<!--
| Oct 10  | [Selecting a research design](){target="_blank"} |
| Oct 15  | [Review](){target="_blank"} |
| Oct 17  | [Midterm](){target="_blank"} |
| Oct 22  | [Midterm results, introduction of final project](){target="_blank"} |
-->


## M4: Specify Your Methods

By the end of this module, you should be able to:

* Select the best method of data collection given study objectives and resources
* Devise a sampling strategy to meet study objectives and resources
* Design a high-powered study

<br>

#### Class Sessions

| Date    | Session             | 
|:---------|:--------------------|
| Oct 24  | 4.1 Participants, sampling, and recruitment |
| Oct 29  | 4.2 Sample size and analysis plans |
| Oct 31  | 4.3 Quantitative data collection procedures |
| Nov 5  | 4.4 Qualitative data collection procesures |
<!--
| Oct 24  | [4.1 Participants, sampling, and recruitment](){target="_blank"} |
| Oct 29  | [4.2 Sample size and analysis plans](){target="_blank"} |
| Oct 31  | [4.3 Quantitative data collection procedures](){target="_blank"} |
| Nov 5  | [4.4 Qualitative data collection procesures](){target="_blank"} |
-->


<br>

#### Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| TBA                           | TBA      |


## M5: Practice Good Science

By the end of this module, you should be able to:

* Describe common challenges when building research collaborations and articulate strategies for being a good collaborator
* Understand the process of ethical review
* Explain the benefits of open science practices to colleagues

<br>

#### Class Sessions

| Date    | Session             | 
|:---------|:--------------------|
| Nov 7  | 5.1 Collaborations |
| Nov 12  | 5.2 Research ethics |
| Nov 14  | 5.3 Open science |
<!--
| Nov 7  | [5.1 Collaborations](){target="_blank"} |
| Nov 12  | [5.2 Research ethics](){target="_blank"} |
| Nov 14  | [5.3 Open science](){target="_blank"} |
-->


<br>

#### Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| TBA                           | TBA      |


## M6: Make an Impact

By the end of this module, you should be able to:

* Understand how scientists share their work by publishing and giving talks at conferences
* Make a plan to promote the use of research in policymaking

<br>

#### Class Sessions

| Date    | Session             | 
|:---------|:--------------------|
| Nov 19  | 6.1 Sharing your work |
| Nov 21  | 6.2 Impacting policy and practice |
<!--
| Nov 19  | [6.1 Sharing your work](){target="_blank"} |
| Nov 21  | [6.2 Impacting policy and practice](){target="_blank"} |
-->


<br>

#### Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| TBA                           | TBA      |


## Final Project

| Date    | Session             | 
|:---------|:--------------------|
| Nov 26  | Course review |
| Dec 3  | Peer review (undergrad) |
| Dec 5  | Proposal revisions (undergrad) |
| TBA  | TBA |
<!--
| Nov 26  | [Course review](){target="_blank"} |
| Dec 3  | [Peer review (undergrad)](){target="_blank"} |
| Dec 5  | [Proposal revisions (undergrad)](){target="_blank"} |
| TBA  | [TBA](){target="_blank"} |
-->


## Get Help

Getting help is easy. Try the following, in order of priority:

1. Ask a question in class.
2. Post a question to Piazza. This is a great platform that turns your questions and answers into public goods. We'll strive to answer every question within hours (often minutes). You can post anonymously to your peers if desired, so there really are no "dumb" questions.
3. If you need additional help after trying #1 and #2, attend office hours or set up individual or small-group meetings. 

Please limit your emails to personal matters that are not appropriate for class or Piazza. "I don't understand power calculations" is not a personal matter. Emails like this will probably go unanswered, whereas Piazza messages will be rewarded with snappy replies since they benefit everyone.

Enrolled students can access Piazza [here](https://piazza.com/duke/fall2019/glhlth702/home){target="_blank"}.

## Not at Duke?

**Learners**: You're welcome to use any resources you find on this site. A Coursera course is in development.

**Instructors**: Please visit [themethodsection.com](https://themethodsection.com/){target="_blank"} to request access to additional resources. Course materials are shared under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.

## About this Website

Course materials are delivered via [`learnr`](https://rstudio.github.io/learnr/){target="_blank"} tutorials hosted on a [RStudio Connect](https://www.rstudio.com/products/connect/){target="_blank"} server hosted by Duke University. A big thanks to [RStudio](https://www.rstudio.com/){target="_blank"} for providing an academic license, and to Duke OIT for helping to setup and manage the server.